<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 
			
  
    <meta name="twitter:card" content="summary"/>
    
      <meta name="twitter:image" content="/images/avatar.png" />
    
  
  
  <meta name="twitter:title" content="Build a letter recognition classifier"/>
  <meta name="twitter:description" content="[Dec 28, 2017] In this analysis i’ll develop a model that will predict the hand-written capital letters (english) displayed in a picture, using various of it&#39;s attributes"/>
  
    <meta name="twitter:site" content="@your_twitter_id"/>
  
  
  
  
    <meta name="twitter:creator" content="@"/>
  



		
		
		<meta name="description" content="Site Description">
		<meta name="generator" content="Hugo 0.36.1" />
		<title>Build a letter recognition classifier &middot; Manos Antoniou</title>
		<link rel="shortcut icon" href="/images/favicon.ico">
		<link rel="stylesheet" href="/css/style.css">
		<link rel="stylesheet" href="/css/highlight.css">

		
		<link rel="stylesheet" href="/css/font-awesome.min.css">
		

		
		<link href="/index.xml" rel="alternate" type="application/rss+xml" title="Manos Antoniou" />
		

		
	</head>

    <body>
       <nav class="main-nav">
	
	
		<a href='/'> <span class="arrow">←</span>Home</a>
	
	<a href='/about'>About</a>
	<a href='/tags'>Tags</a>
	<a href='https://www.linkedin.com/in/manos-antoniou-a558001b/'>LinkedIn</a>


	

	
	<a class="cta" href="/index.xml">Subscribe</a>
	
</nav>


        <section id="wrapper" class="post">
            <article>
                <header>
                    <h1>
                        Build a letter recognition classifier
                    </h1>
                    <h2 class="headline">
                    Dec 28, 2017 00:00
                    · 14089 words
                    · 67 minute read
                      <span class="tags">
                      
                      
                          
                              <a href="/tags/classification">classification</a>
                          
                              <a href="/tags/clustering">clustering</a>
                          
                              <a href="/tags/k-nn">k-NN</a>
                          
                              <a href="/tags/svd">SVD</a>
                          
                      
                      
                      </span>
                    </h2>
                </header>
                
                  
                
                <section id="post-body">
                    <p>In this analysis i’ll develop a model that will predict the hand-written capital letters (english) displayed in a picture, using various of it’s attributes.</p>
<div id="introduction" class="section level1">
<h1>INTRODUCTION</h1>
<p><strong>Dataset Information</strong></p>
<p>This data set was originally used in the paper of <strong>P. W. Frey and D. J. Slate.“Letter Recognition Using Holland-style Adaptive Classifiers”</strong> (Machine Learning Vol 6 #2 March 91). It investigated the ability of several variations of Holland-style adaptive classifier systems to learn to correctly guess the letter categories associated with vectors of 16 integer attributes extracted from raster scan images of the letters. The actual data can be found at Letter Recognition Data Set Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/datasets/Letter+Recognition" class="uri">https://archive.ics.uci.edu/ml/datasets/Letter+Recognition</a></p>
<p>The objective is to identify each of a large number of black-and-white rectangular pixel displays as one of the 26 capital letters in the English alphabet. The character images were based on 20 different fonts and each letter within these 20 fonts was randomly distorted to produce a file of unique stimuli. Each stimulus was converted into primitive numerical attributes (statistical moments and edge counts) which were then scaled to fit into a range of integer values from 0 through 15. So in total there are <strong>20000 observations</strong> of <strong>17 variables</strong>. There are no missing values in the data set.</p>
<p><strong>The variables</strong></p>
<ol style="list-style-type: decimal">
<li>lettr capital letter (26 values from A to Z)</li>
<li>x-box horizontal position of box (integer)</li>
<li>y-box vertical position of box (integer)</li>
<li>width width of box (integer)</li>
<li>high height of box (integer)</li>
<li>onpix total # on pixels (integer)</li>
<li>x-bar mean x of on pixels in box (integer)</li>
<li>y-bar mean y of on pixels in box (integer)</li>
<li>x2bar mean x variance (integer)</li>
<li>y2bar mean y variance (integer)</li>
<li>xybar mean x y correlation (integer)</li>
<li>x2ybr mean of x * x * y (integer)</li>
<li>xy2br mean of x * y * y (integer)</li>
<li>x-ege mean edge count left to right (integer)</li>
<li>xegvy correlation of x-ege with y (integer)</li>
<li>y-ege mean edge count bottom to top (integer)</li>
<li>yegvx correlation of y-ege with x (integer)</li>
</ol>
</div>
<div id="pre-proccessing" class="section level1">
<h1>PRE-PROCCESSING</h1>
<p>Since the original data set didn’t contain any names on the variables, after i imported the data in R environment, i assigned the appropriate variable names. That was completed with the help of <strong>letter-recognition.names</strong> text file which accompanied the original data.</p>
<p>During the development of the prediction model, in order to predict the letter on new observations, at first we’ve used all variables. Then we excluded some of the 4 correllated variables and finally we’ve used the variables created from the SVD algorithm instead of the original.</p>
<p>Before we apply the hierarchical clustering, we created a data set with each letter as one observation and the average of each variable, as a distinct variable <strong>(named letter.cluster)</strong>.</p>
<pre class="r"><code># Load Libraries
library(tidyverse)
library(stringr)
library(scales)
library(ggthemes)
library(corrplot)
library(caret)
library(gmodels)
library(class)
library(ggdendro)


# DATA WRANGLING ###############################################################
# Insert dataset
letter &lt;- read.table(&quot;/Users/manos/Dropbox/Projects/R/Data/letter-recognition.data&quot;,
                  sep = &quot;,&quot;)

# Create vector with new variable names
name &lt;- c(&quot;lettr&quot;, &quot;x-box&quot;, &quot;y-box&quot;, &quot;width&quot;, &quot;high&quot;, &quot;onpix&quot;, &quot;x-bar&quot;, &quot;y-bar&quot;, 
          &quot;x2bar&quot;, &quot;y2bar&quot;, &quot;xybar&quot;, &quot;x2ybr&quot;, &quot;xy2br&quot;, &quot;x-ege&quot;, &quot;xegvy&quot;, &quot;y-ege&quot;,
          &quot;yegvx&quot;)

# Change the variable names of the dataset
names(letter) &lt;- name

# Make it a tibble
letter &lt;- as_data_frame(letter)

# Check for missing values
sum(is.na(letter))</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code># Create the summary dataset
letter.cluster &lt;- letter %&gt;% 
  group_by(lettr) %&gt;% 
  summarise_each(funs(mean))</code></pre>
</div>
<div id="exploratory-analysis" class="section level1">
<h1>EXPLORATORY ANALYSIS</h1>
<p>In order to have an overview of the dataset’s variability, i produced a box-plot matrix of all variables and each letter on the x-axis</p>
<pre class="r"><code># Plot a box-plot for each letter and variable
letter %&gt;% 
  gather(&quot;type&quot;, &quot;n&quot;, 2:17) %&gt;% 
  ggplot()+
  geom_boxplot(aes(x = lettr, y = n), outlier.size = .5, fill = &quot;steelblue2&quot;, alpha = .7)+
  facet_grid(type ~.)+
  labs(y = &quot;&quot;, x = &quot;&quot;, 
       title = &quot;Box-Plots of all variables for each letter&quot;, 
       subtitle = &quot;&quot;)+
 theme_fivethirtyeight()</code></pre>
<p><img src="/post/2017-12-28-build-a-letter-recognition-classifier_files/figure-html/exploratory%20box-plot-1.png" width="672" /></p>
<p>It looks that in some variables, the letters levels have significant different variance, than others. In particular, in <strong>y-box</strong> and <strong>high</strong> variables the different letters don’t seem to have any significant differences. On the other hand in <strong>x-bar</strong>, <strong>x2ybr</strong>, <strong>y-bar</strong>, <strong>y-ege</strong> variables the different letters seem to have large differences.</p>
<p>We should check for correlated variables in the data set. Below you can see a correlogram of the data set variables.</p>
<pre class="r"><code># Plot a correlogram to check for correlations
corrplot(cor(letter[,2:17]), method=&quot;number&quot;, type = &quot;lower&quot;, number.cex = .6)</code></pre>
<p><img src="/post/2017-12-28-build-a-letter-recognition-classifier_files/figure-html/exploratory%20correlogram-1.png" width="672" /></p>
<p>It seems that the first 4 variables <strong>(x-box, y-box, width, high)</strong> are quite correlated. Especially x-box &amp; width (0.85) and y-box &amp; high (0.82) are highly correlated.</p>
</div>
<div id="modelling" class="section level1">
<h1>MODELLING</h1>
<p>An interesting insight that could be obtained from the data set is to try to predict the letter based on the variables produced by the digitized image. Classification is the problem of identifying to which of a set of categories (sub-populations) a new observation belongs, on the basis of a training set of data containing observations (or instances) whose category membership is known. So we must develop a model that classifies (categorize) every observation (case) to one of the 26 letters of the alphabet.</p>
<div id="k-nearest-neighbors-k-nn" class="section level2">
<h2><strong>K-Nearest Neighbors (k-NN)</strong></h2>
<p>The K-nearest neighbors (kNN) algorithm used, in order to classify observations in a certain category (letter) by using the rest of the variables in the data set. It begins with a training data set made up of examples that are classified into several categories, as labeled by a nominal variable. Assume that we have a test data set containing unlabeled examples that otherwise have the same features as the training data. For each record in the test data set, kNN identifies k records in the training data that are the “nearest” in similarity, where k is an integer specified in advance. The unlabeled test instance is assigned the class of the majority of the k-nearest neighbors. We splitted the data set into a training data set (containing 70 % of the original data set observations) in which we build the classification model and a testing data set (containing the rest of the original data set observations - 30%) in which we tested the model we build before. The results are presented in the “results” section.</p>
<pre class="r"><code># Create a vector with the 70% of the dataset with respect to letter
set.seed(10)
inTrain = createDataPartition(letter$lettr, p = .7)[[1]]

# Assign the 70% of observations to training data
training &lt;- letter[inTrain, -1]
training.lettr &lt;- c(t(letter[inTrain, 1]))

# Assign the remaining 30 % of observations to testing data
testing &lt;- letter[-inTrain, -1]
testing.lettr &lt;- c(t(letter[-inTrain, 1]))


# Run knn algorithm on training dataset
# Create the knn model
knn_model &lt;- knn(train = training, test = testing, cl = training.lettr, k = 3)

# Create a table in order to check the performance of the classification model
t &lt;- CrossTable(x = testing.lettr,y = knn_model,
           prop.chisq=FALSE)</code></pre>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  5985 
## 
##  
##               | knn_model 
## testing.lettr |         A |         B |         C |         D |         E |         F |         G |         H |         I |         J |         K |         L |         M |         N |         O |         P |         Q |         R |         S |         T |         U |         V |         W |         X |         Y |         Z | Row Total | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             A |       235 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |       236 | 
##               |     0.996 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.039 | 
##               |     0.975 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.039 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             B |         0 |       212 |         0 |         0 |         3 |         0 |         0 |         7 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |         2 |         3 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |       229 | 
##               |     0.000 |     0.926 |     0.000 |     0.000 |     0.013 |     0.000 |     0.000 |     0.031 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.009 |     0.013 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.038 | 
##               |     0.000 |     0.895 |     0.000 |     0.000 |     0.013 |     0.000 |     0.000 |     0.033 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.009 |     0.014 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.035 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             C |         0 |         0 |       214 |         0 |         1 |         0 |         1 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         2 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |         0 |       220 | 
##               |     0.000 |     0.000 |     0.973 |     0.000 |     0.005 |     0.000 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.005 |     0.000 |     0.000 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.037 | 
##               |     0.000 |     0.000 |     0.977 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.008 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.036 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             D |         0 |         2 |         0 |       223 |         0 |         0 |         0 |         8 |         0 |         0 |         0 |         0 |         0 |         2 |         1 |         0 |         0 |         3 |         1 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |       241 | 
##               |     0.000 |     0.008 |     0.000 |     0.925 |     0.000 |     0.000 |     0.000 |     0.033 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.008 |     0.004 |     0.000 |     0.000 |     0.012 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.040 | 
##               |     0.000 |     0.008 |     0.000 |     0.914 |     0.000 |     0.000 |     0.000 |     0.038 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.009 |     0.004 |     0.000 |     0.000 |     0.013 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.037 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             E |         0 |         1 |         0 |         0 |       221 |         2 |         2 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         2 |         0 |         1 |       230 | 
##               |     0.000 |     0.004 |     0.000 |     0.000 |     0.961 |     0.009 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.009 |     0.000 |     0.004 |     0.038 | 
##               |     0.000 |     0.004 |     0.000 |     0.000 |     0.932 |     0.008 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.009 |     0.000 |     0.005 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.037 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             F |         0 |         1 |         1 |         0 |         0 |       219 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         5 |         0 |         0 |         0 |         3 |         0 |         1 |         0 |         1 |         0 |         0 |       232 | 
##               |     0.000 |     0.004 |     0.004 |     0.000 |     0.000 |     0.944 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.022 |     0.000 |     0.000 |     0.000 |     0.013 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.039 | 
##               |     0.000 |     0.004 |     0.005 |     0.000 |     0.000 |     0.905 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.022 |     0.000 |     0.000 |     0.000 |     0.013 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.037 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             G |         0 |         0 |         1 |         0 |         3 |         0 |       221 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |         2 |         0 |         1 |         0 |         1 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |       231 | 
##               |     0.000 |     0.000 |     0.004 |     0.000 |     0.013 |     0.000 |     0.957 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.009 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.039 | 
##               |     0.000 |     0.000 |     0.005 |     0.000 |     0.013 |     0.000 |     0.944 |     0.000 |     0.000 |     0.000 |     0.005 |     0.000 |     0.000 |     0.000 |     0.008 |     0.000 |     0.004 |     0.000 |     0.005 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.037 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             H |         0 |         1 |         0 |         8 |         0 |         0 |         5 |       185 |         0 |         0 |         9 |         0 |         1 |         0 |         1 |         2 |         0 |         7 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |       220 | 
##               |     0.000 |     0.005 |     0.000 |     0.036 |     0.000 |     0.000 |     0.023 |     0.841 |     0.000 |     0.000 |     0.041 |     0.000 |     0.005 |     0.000 |     0.005 |     0.009 |     0.000 |     0.032 |     0.000 |     0.000 |     0.000 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.037 | 
##               |     0.000 |     0.004 |     0.000 |     0.033 |     0.000 |     0.000 |     0.021 |     0.869 |     0.000 |     0.000 |     0.041 |     0.000 |     0.004 |     0.000 |     0.004 |     0.009 |     0.000 |     0.031 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.031 |     0.000 |     0.000 |     0.002 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             I |         0 |         1 |         0 |         1 |         0 |         0 |         0 |         0 |       217 |         7 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |       226 | 
##               |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.960 |     0.031 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.038 | 
##               |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.956 |     0.032 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.036 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             J |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |        10 |       212 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |       224 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.045 |     0.946 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.037 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.005 |     0.044 |     0.968 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.002 |     0.035 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             K |         0 |         0 |         0 |         1 |         4 |         0 |         0 |         4 |         0 |         0 |       199 |         1 |         0 |         0 |         0 |         0 |         0 |         7 |         1 |         0 |         0 |         0 |         0 |         4 |         0 |         0 |       221 | 
##               |     0.000 |     0.000 |     0.000 |     0.005 |     0.018 |     0.000 |     0.000 |     0.018 |     0.000 |     0.000 |     0.900 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.032 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.018 |     0.000 |     0.000 |     0.037 | 
##               |     0.000 |     0.000 |     0.000 |     0.004 |     0.017 |     0.000 |     0.000 |     0.019 |     0.000 |     0.000 |     0.900 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.031 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.017 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.033 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             L |         0 |         0 |         0 |         0 |         1 |         0 |         3 |         0 |         0 |         0 |         2 |       220 |         0 |         0 |         0 |         0 |         0 |         2 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |       228 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.013 |     0.000 |     0.000 |     0.000 |     0.009 |     0.965 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.038 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.013 |     0.000 |     0.000 |     0.000 |     0.009 |     0.982 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.037 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             M |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |       234 |         1 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |       237 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.987 |     0.004 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.040 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.987 |     0.004 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.039 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             N |         1 |         0 |         0 |         1 |         0 |         0 |         0 |         3 |         0 |         0 |         0 |         1 |         1 |       219 |         3 |         0 |         1 |         3 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |       234 | 
##               |     0.004 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.013 |     0.000 |     0.000 |     0.000 |     0.004 |     0.004 |     0.936 |     0.013 |     0.000 |     0.004 |     0.013 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.039 | 
##               |     0.004 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.014 |     0.000 |     0.000 |     0.000 |     0.004 |     0.004 |     0.948 |     0.013 |     0.000 |     0.004 |     0.013 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.037 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             O |         0 |         0 |         3 |         2 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |       217 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |       225 | 
##               |     0.000 |     0.000 |     0.013 |     0.009 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.964 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.038 | 
##               |     0.000 |     0.000 |     0.014 |     0.008 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.916 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.036 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             P |         0 |         0 |         0 |         0 |         0 |        19 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |       216 |         2 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |       240 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.079 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.900 |     0.008 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.040 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.079 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.964 |     0.009 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.003 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.036 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             Q |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         8 |         0 |       224 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |       234 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.034 |     0.000 |     0.957 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.039 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.034 |     0.000 |     0.974 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.037 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             R |         0 |        11 |         0 |         3 |         0 |         0 |         0 |         2 |         0 |         0 |         6 |         0 |         0 |         6 |         0 |         0 |         0 |       198 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |       227 | 
##               |     0.000 |     0.048 |     0.000 |     0.013 |     0.000 |     0.000 |     0.000 |     0.009 |     0.000 |     0.000 |     0.026 |     0.000 |     0.000 |     0.026 |     0.000 |     0.000 |     0.000 |     0.872 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.038 | 
##               |     0.000 |     0.046 |     0.000 |     0.012 |     0.000 |     0.000 |     0.000 |     0.009 |     0.000 |     0.000 |     0.027 |     0.000 |     0.000 |     0.026 |     0.000 |     0.000 |     0.000 |     0.872 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.002 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.033 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             S |         0 |         1 |         0 |         4 |         1 |         0 |         1 |         2 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |       213 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |       224 | 
##               |     0.000 |     0.004 |     0.000 |     0.018 |     0.004 |     0.000 |     0.004 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.951 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.037 | 
##               |     0.000 |     0.004 |     0.000 |     0.016 |     0.004 |     0.000 |     0.004 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.964 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.005 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.036 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             T |         0 |         1 |         0 |         1 |         0 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |       229 |         0 |         1 |         0 |         1 |         3 |         0 |       238 | 
##               |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.962 |     0.000 |     0.004 |     0.000 |     0.004 |     0.013 |     0.000 |     0.040 | 
##               |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.954 |     0.000 |     0.004 |     0.000 |     0.004 |     0.013 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.038 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             U |         4 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |       239 |         0 |         0 |         0 |         0 |         0 |       243 | 
##               |     0.016 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.984 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.041 | 
##               |     0.017 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.988 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.040 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             V |         0 |         4 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         1 |         0 |         0 |         0 |         0 |         0 |       218 |         3 |         0 |         1 |         0 |       229 | 
##               |     0.000 |     0.017 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.952 |     0.013 |     0.000 |     0.004 |     0.000 |     0.038 | 
##               |     0.000 |     0.017 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.956 |     0.013 |     0.000 |     0.004 |     0.000 |           | 
##               |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.036 |     0.001 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             W |         0 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         1 |         0 |         0 |         0 |         3 |       219 |         0 |         0 |         0 |       225 | 
##               |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.013 |     0.973 |     0.000 |     0.000 |     0.000 |     0.038 | 
##               |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.013 |     0.978 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.037 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             X |         0 |         0 |         0 |         0 |         3 |         0 |         0 |         0 |         0 |         0 |         4 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         1 |         1 |         2 |         0 |         0 |       224 |         0 |         0 |       236 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.013 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.017 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.004 |     0.004 |     0.008 |     0.000 |     0.000 |     0.949 |     0.000 |     0.000 |     0.039 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.013 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.018 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.005 |     0.004 |     0.008 |     0.000 |     0.000 |     0.961 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.037 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             Y |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         5 |         0 |         0 |         0 |         0 |       228 |         0 |       235 | 
##               |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.021 |     0.000 |     0.000 |     0.000 |     0.000 |     0.970 |     0.000 |     0.039 | 
##               |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.021 |     0.000 |     0.000 |     0.000 |     0.000 |     0.974 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.038 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             Z |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         0 |         0 |         2 |         0 |         0 |         0 |         0 |         0 |       217 |       220 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.005 |     0.000 |     0.000 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.986 |     0.037 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.008 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.991 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.036 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##  Column Total |       241 |       237 |       219 |       244 |       237 |       242 |       234 |       213 |       227 |       219 |       221 |       224 |       237 |       231 |       237 |       224 |       230 |       227 |       221 |       240 |       242 |       228 |       224 |       233 |       234 |       219 |      5985 | 
##               |     0.040 |     0.040 |     0.037 |     0.041 |     0.040 |     0.040 |     0.039 |     0.036 |     0.038 |     0.037 |     0.037 |     0.037 |     0.040 |     0.039 |     0.040 |     0.037 |     0.038 |     0.038 |     0.037 |     0.040 |     0.040 |     0.038 |     0.037 |     0.039 |     0.039 |     0.037 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
## 
## </code></pre>
<pre class="r"><code># Calculate prediction success rate for all letters
mean(diag(t$prop.col))</code></pre>
<pre><code>## [1] 0.9478915</code></pre>
<pre class="r"><code># Check prediction success rate for each letter
diag(t$prop.col)</code></pre>
<pre><code>##         A         B         C         D         E         F         G 
## 0.9751037 0.8945148 0.9771689 0.9139344 0.9324895 0.9049587 0.9444444 
##         H         I         J         K         L         M         N 
## 0.8685446 0.9559471 0.9680365 0.9004525 0.9821429 0.9873418 0.9480519 
##         O         P         Q         R         S         T         U 
## 0.9156118 0.9642857 0.9739130 0.8722467 0.9638009 0.9541667 0.9876033 
##         V         W         X         Y         Z 
## 0.9561404 0.9776786 0.9613734 0.9743590 0.9908676</code></pre>
<p>The accuracy obtained from the nearest neighbors classification algorithm is around <strong>94,8%</strong>. I’ve used 3 nearest neighbors (k=3) for building the final model. Alternative number of neighbors (4,5,6,7 etc) produced slightly lower accuracy rate (94.3% - 94,7%). The model is better at predicting some letters, such as L, M, U, Z with more than 98% accuracy rate. On the other hand, other letters such as H, R, B are more difficult to predict (&lt;90% accuracy rate). In the plot below you can see each letter accuracy rate of the final model.</p>
<pre class="r"><code># Create a data set with the accuracy rate of each letter
letters &lt;- diag(t$prop.col) %&gt;% 
  as.data.frame()

# Make the appropriate transformations in order to plot
letters$letter &lt;- rownames(letters)

# Plot the accuracy rate per letter
ggplot(letters)+
  geom_bar(aes(x = letter, y = .), stat=&quot;identity&quot;, fill = &quot;steelblue2&quot;, alpha = .7)+
    scale_y_continuous(labels=percent) +
  labs(title = &quot;Accuracy rate % per letter (K-NN algorithm)&quot;, 
       x = &quot;&quot;, y = &quot;Accuracy rate %&quot;, subtittle = &quot;&quot;)+
 theme_fivethirtyeight()</code></pre>
<p><img src="/post/2017-12-28-build-a-letter-recognition-classifier_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
</div>
<div id="singular-value-decomposition-svd" class="section level2">
<h2><strong>Singular Value Decomposition (SVD)</strong></h2>
<p>Since i discovered that there are some correlated variables in the data set, i applied the SVD algorithm in order to create a data set with uncorrelated variables. SVD is an algebraic tool that has many potential uses such as:</p>
<ul>
<li>Dimensionality reduction</li>
<li>Indexing (LSI)</li>
<li>Visualization/clustering of high-dimensional objects</li>
<li>Similarity computations/outlier detection</li>
<li>Rule mining, treatment of missing/wrong values</li>
</ul>
<p>Below i created a new dataset with the new svd variables and build a new model using k-NN algorithm.</p>
<pre class="r"><code># Create an in Dataset 
letter.svd &lt;- svd(letter[,2:17])

# Create a dataset with the SVD values
letter2 &lt;- as_data_frame(cbind(letter[,1],letter.svd$u))

# Keep specific SVD variables
letter2 &lt;- letter2[,1:8]

# Create a vector with the 70% of the dataset with respect to letter
set.seed(10)
inTrain = createDataPartition(letter2$lettr, p = .7)[[1]]

# Assign the 70% of observations to training data
training &lt;- letter2[inTrain, -1]
training.lettr &lt;- c(t(letter2[inTrain, 1]))

# Assign the remaining 30 % of observations to testing data
testing &lt;- letter2[-inTrain, -1]
testing.lettr &lt;- c(t(letter2[-inTrain, 1]))


# Run knn algorithm on training dataset
# Create the knn model
knn_model.svd &lt;- knn(train = training, test = testing, cl = training.lettr, k = 3)

# Create a table in order to check the performance of the classification model
s &lt;- CrossTable(x = testing.lettr,y = knn_model.svd,
           prop.chisq=FALSE)</code></pre>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  5985 
## 
##  
##               | knn_model.svd 
## testing.lettr |         A |         B |         C |         D |         E |         F |         G |         H |         I |         J |         K |         L |         M |         N |         O |         P |         Q |         R |         S |         T |         U |         V |         W |         X |         Y |         Z | Row Total | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             A |       212 |         2 |         0 |         2 |         0 |         0 |         3 |         3 |         0 |         0 |         1 |         0 |         1 |         1 |         2 |         1 |         0 |         4 |         0 |         1 |         0 |         0 |         0 |         0 |         3 |         0 |       236 | 
##               |     0.898 |     0.008 |     0.000 |     0.008 |     0.000 |     0.000 |     0.013 |     0.013 |     0.000 |     0.000 |     0.004 |     0.000 |     0.004 |     0.004 |     0.008 |     0.004 |     0.000 |     0.017 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.013 |     0.000 |     0.039 | 
##               |     0.910 |     0.008 |     0.000 |     0.008 |     0.000 |     0.000 |     0.012 |     0.015 |     0.000 |     0.000 |     0.005 |     0.000 |     0.004 |     0.004 |     0.008 |     0.005 |     0.000 |     0.016 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.013 |     0.000 |           | 
##               |     0.035 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             B |         1 |       165 |         0 |         3 |         3 |         1 |         2 |         4 |         3 |         1 |         2 |         0 |         1 |         1 |         1 |         0 |         2 |        14 |        17 |         0 |         0 |         2 |         1 |         1 |         1 |         3 |       229 | 
##               |     0.004 |     0.721 |     0.000 |     0.013 |     0.013 |     0.004 |     0.009 |     0.017 |     0.013 |     0.004 |     0.009 |     0.000 |     0.004 |     0.004 |     0.004 |     0.000 |     0.009 |     0.061 |     0.074 |     0.000 |     0.000 |     0.009 |     0.004 |     0.004 |     0.004 |     0.013 |     0.038 | 
##               |     0.004 |     0.655 |     0.000 |     0.012 |     0.013 |     0.004 |     0.008 |     0.021 |     0.013 |     0.005 |     0.010 |     0.000 |     0.004 |     0.004 |     0.004 |     0.000 |     0.009 |     0.055 |     0.074 |     0.000 |     0.000 |     0.009 |     0.004 |     0.004 |     0.004 |     0.014 |           | 
##               |     0.000 |     0.028 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.002 |     0.003 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             C |         0 |         0 |       198 |         0 |         3 |         0 |         8 |         1 |         0 |         0 |         0 |         1 |         0 |         0 |         3 |         0 |         1 |         1 |         0 |         1 |         3 |         0 |         0 |         0 |         0 |         0 |       220 | 
##               |     0.000 |     0.000 |     0.900 |     0.000 |     0.014 |     0.000 |     0.036 |     0.005 |     0.000 |     0.000 |     0.000 |     0.005 |     0.000 |     0.000 |     0.014 |     0.000 |     0.005 |     0.005 |     0.000 |     0.005 |     0.014 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.037 | 
##               |     0.000 |     0.000 |     0.925 |     0.000 |     0.013 |     0.000 |     0.033 |     0.005 |     0.000 |     0.000 |     0.000 |     0.005 |     0.000 |     0.000 |     0.013 |     0.000 |     0.004 |     0.004 |     0.000 |     0.004 |     0.012 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.033 |     0.000 |     0.001 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             D |         3 |         6 |         0 |       184 |         2 |         2 |         2 |         3 |         2 |         2 |         2 |         1 |         0 |         1 |         4 |         0 |         1 |        16 |         3 |         0 |         0 |         0 |         0 |         3 |         1 |         3 |       241 | 
##               |     0.012 |     0.025 |     0.000 |     0.763 |     0.008 |     0.008 |     0.008 |     0.012 |     0.008 |     0.008 |     0.008 |     0.004 |     0.000 |     0.004 |     0.017 |     0.000 |     0.004 |     0.066 |     0.012 |     0.000 |     0.000 |     0.000 |     0.000 |     0.012 |     0.004 |     0.012 |     0.040 | 
##               |     0.013 |     0.024 |     0.000 |     0.751 |     0.008 |     0.009 |     0.008 |     0.015 |     0.009 |     0.009 |     0.010 |     0.005 |     0.000 |     0.004 |     0.017 |     0.000 |     0.004 |     0.063 |     0.013 |     0.000 |     0.000 |     0.000 |     0.000 |     0.012 |     0.004 |     0.014 |           | 
##               |     0.001 |     0.001 |     0.000 |     0.031 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.003 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.001 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             E |         0 |         3 |         3 |         0 |       178 |         1 |         5 |         0 |         2 |         0 |         1 |         2 |         0 |         0 |         0 |         0 |         2 |         2 |         8 |         0 |         0 |         2 |         0 |        19 |         0 |         2 |       230 | 
##               |     0.000 |     0.013 |     0.013 |     0.000 |     0.774 |     0.004 |     0.022 |     0.000 |     0.009 |     0.000 |     0.004 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.009 |     0.009 |     0.035 |     0.000 |     0.000 |     0.009 |     0.000 |     0.083 |     0.000 |     0.009 |     0.038 | 
##               |     0.000 |     0.012 |     0.014 |     0.000 |     0.748 |     0.004 |     0.020 |     0.000 |     0.009 |     0.000 |     0.005 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.009 |     0.008 |     0.035 |     0.000 |     0.000 |     0.009 |     0.000 |     0.075 |     0.000 |     0.010 |           | 
##               |     0.000 |     0.001 |     0.001 |     0.000 |     0.030 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.003 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             F |         0 |         4 |         0 |         2 |         1 |       186 |         0 |         1 |         4 |         3 |         0 |         1 |         0 |         1 |         0 |         7 |         0 |         0 |         3 |        11 |         0 |         2 |         0 |         0 |         5 |         1 |       232 | 
##               |     0.000 |     0.017 |     0.000 |     0.009 |     0.004 |     0.802 |     0.000 |     0.004 |     0.017 |     0.013 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.030 |     0.000 |     0.000 |     0.013 |     0.047 |     0.000 |     0.009 |     0.000 |     0.000 |     0.022 |     0.004 |     0.039 | 
##               |     0.000 |     0.016 |     0.000 |     0.008 |     0.004 |     0.802 |     0.000 |     0.005 |     0.018 |     0.014 |     0.000 |     0.005 |     0.000 |     0.004 |     0.000 |     0.032 |     0.000 |     0.000 |     0.013 |     0.044 |     0.000 |     0.009 |     0.000 |     0.000 |     0.022 |     0.005 |           | 
##               |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.031 |     0.000 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.002 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             G |         1 |         6 |         1 |         1 |         1 |         0 |       187 |         2 |         0 |         0 |         3 |         1 |         5 |         1 |         4 |         0 |         6 |         6 |         1 |         0 |         2 |         1 |         1 |         1 |         0 |         0 |       231 | 
##               |     0.004 |     0.026 |     0.004 |     0.004 |     0.004 |     0.000 |     0.810 |     0.009 |     0.000 |     0.000 |     0.013 |     0.004 |     0.022 |     0.004 |     0.017 |     0.000 |     0.026 |     0.026 |     0.004 |     0.000 |     0.009 |     0.004 |     0.004 |     0.004 |     0.000 |     0.000 |     0.039 | 
##               |     0.004 |     0.024 |     0.005 |     0.004 |     0.004 |     0.000 |     0.760 |     0.010 |     0.000 |     0.000 |     0.015 |     0.005 |     0.022 |     0.004 |     0.017 |     0.000 |     0.026 |     0.024 |     0.004 |     0.000 |     0.008 |     0.004 |     0.004 |     0.004 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.031 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.001 |     0.000 |     0.001 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             H |         2 |        11 |         1 |        10 |         1 |         1 |         8 |       140 |         0 |         2 |         6 |         1 |         1 |         4 |         1 |         3 |         2 |        15 |         0 |         3 |         0 |         2 |         0 |         2 |         4 |         0 |       220 | 
##               |     0.009 |     0.050 |     0.005 |     0.045 |     0.005 |     0.005 |     0.036 |     0.636 |     0.000 |     0.009 |     0.027 |     0.005 |     0.005 |     0.018 |     0.005 |     0.014 |     0.009 |     0.068 |     0.000 |     0.014 |     0.000 |     0.009 |     0.000 |     0.009 |     0.018 |     0.000 |     0.037 | 
##               |     0.009 |     0.044 |     0.005 |     0.041 |     0.004 |     0.004 |     0.033 |     0.722 |     0.000 |     0.009 |     0.030 |     0.005 |     0.004 |     0.017 |     0.004 |     0.014 |     0.009 |     0.059 |     0.000 |     0.012 |     0.000 |     0.009 |     0.000 |     0.008 |     0.018 |     0.000 |           | 
##               |     0.000 |     0.002 |     0.000 |     0.002 |     0.000 |     0.000 |     0.001 |     0.023 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.001 |     0.000 |     0.003 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             I |         0 |         3 |         0 |         1 |         3 |         2 |         0 |         0 |       202 |         3 |         1 |         0 |         0 |         0 |         0 |         4 |         0 |         2 |         3 |         0 |         0 |         0 |         0 |         1 |         0 |         1 |       226 | 
##               |     0.000 |     0.013 |     0.000 |     0.004 |     0.013 |     0.009 |     0.000 |     0.000 |     0.894 |     0.013 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.018 |     0.000 |     0.009 |     0.013 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.004 |     0.038 | 
##               |     0.000 |     0.012 |     0.000 |     0.004 |     0.013 |     0.009 |     0.000 |     0.000 |     0.906 |     0.014 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.018 |     0.000 |     0.008 |     0.013 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.005 |           | 
##               |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.034 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             J |         0 |         5 |         0 |         4 |         1 |         0 |         1 |         1 |         5 |       194 |         0 |         1 |         0 |         0 |         4 |         1 |         0 |         2 |         1 |         2 |         0 |         0 |         0 |         2 |         0 |         0 |       224 | 
##               |     0.000 |     0.022 |     0.000 |     0.018 |     0.004 |     0.000 |     0.004 |     0.004 |     0.022 |     0.866 |     0.000 |     0.004 |     0.000 |     0.000 |     0.018 |     0.004 |     0.000 |     0.009 |     0.004 |     0.009 |     0.000 |     0.000 |     0.000 |     0.009 |     0.000 |     0.000 |     0.037 | 
##               |     0.000 |     0.020 |     0.000 |     0.016 |     0.004 |     0.000 |     0.004 |     0.005 |     0.022 |     0.915 |     0.000 |     0.005 |     0.000 |     0.000 |     0.017 |     0.005 |     0.000 |     0.008 |     0.004 |     0.008 |     0.000 |     0.000 |     0.000 |     0.008 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.001 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.032 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             K |         1 |         1 |         2 |         0 |         6 |         2 |         2 |         9 |         1 |         0 |       177 |         0 |         0 |         0 |         0 |         0 |         0 |         3 |         3 |         0 |         1 |         2 |         0 |         8 |         3 |         0 |       221 | 
##               |     0.005 |     0.005 |     0.009 |     0.000 |     0.027 |     0.009 |     0.009 |     0.041 |     0.005 |     0.000 |     0.801 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.014 |     0.014 |     0.000 |     0.005 |     0.009 |     0.000 |     0.036 |     0.014 |     0.000 |     0.037 | 
##               |     0.004 |     0.004 |     0.009 |     0.000 |     0.025 |     0.009 |     0.008 |     0.046 |     0.004 |     0.000 |     0.876 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.012 |     0.013 |     0.000 |     0.004 |     0.009 |     0.000 |     0.032 |     0.013 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.002 |     0.000 |     0.000 |     0.030 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.001 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             L |         0 |         0 |         0 |         0 |         4 |         0 |         3 |         2 |         2 |         1 |         0 |       197 |         0 |         1 |         0 |         0 |         7 |         5 |         0 |         2 |         1 |         0 |         0 |         2 |         0 |         1 |       228 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.018 |     0.000 |     0.013 |     0.009 |     0.009 |     0.004 |     0.000 |     0.864 |     0.000 |     0.004 |     0.000 |     0.000 |     0.031 |     0.022 |     0.000 |     0.009 |     0.004 |     0.000 |     0.000 |     0.009 |     0.000 |     0.004 |     0.038 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.017 |     0.000 |     0.012 |     0.010 |     0.009 |     0.005 |     0.000 |     0.925 |     0.000 |     0.004 |     0.000 |     0.000 |     0.031 |     0.020 |     0.000 |     0.008 |     0.004 |     0.000 |     0.000 |     0.008 |     0.000 |     0.005 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.033 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             M |         1 |         0 |         0 |         0 |         1 |         0 |         2 |         1 |         0 |         0 |         0 |         0 |       215 |         1 |         0 |         2 |         0 |         1 |         0 |         0 |         4 |         3 |         6 |         0 |         0 |         0 |       237 | 
##               |     0.004 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.008 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.907 |     0.004 |     0.000 |     0.008 |     0.000 |     0.004 |     0.000 |     0.000 |     0.017 |     0.013 |     0.025 |     0.000 |     0.000 |     0.000 |     0.040 | 
##               |     0.004 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.008 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.931 |     0.004 |     0.000 |     0.009 |     0.000 |     0.004 |     0.000 |     0.000 |     0.016 |     0.013 |     0.026 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.036 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             N |         3 |         0 |         0 |         1 |         0 |         0 |         0 |         3 |         0 |         0 |         0 |         0 |         0 |       212 |         5 |         0 |         2 |         0 |         0 |         0 |         4 |         1 |         2 |         0 |         1 |         0 |       234 | 
##               |     0.013 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.013 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.906 |     0.021 |     0.000 |     0.009 |     0.000 |     0.000 |     0.000 |     0.017 |     0.004 |     0.009 |     0.000 |     0.004 |     0.000 |     0.039 | 
##               |     0.013 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.015 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.876 |     0.021 |     0.000 |     0.009 |     0.000 |     0.000 |     0.000 |     0.016 |     0.004 |     0.009 |     0.000 |     0.004 |     0.000 |           | 
##               |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.035 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             O |         0 |         1 |         2 |         8 |         0 |         0 |         2 |         1 |         0 |         0 |         0 |         0 |         0 |         4 |       186 |         0 |        10 |         6 |         0 |         0 |         3 |         0 |         0 |         2 |         0 |         0 |       225 | 
##               |     0.000 |     0.004 |     0.009 |     0.036 |     0.000 |     0.000 |     0.009 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.018 |     0.827 |     0.000 |     0.044 |     0.027 |     0.000 |     0.000 |     0.013 |     0.000 |     0.000 |     0.009 |     0.000 |     0.000 |     0.038 | 
##               |     0.000 |     0.004 |     0.009 |     0.033 |     0.000 |     0.000 |     0.008 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.017 |     0.788 |     0.000 |     0.044 |     0.024 |     0.000 |     0.000 |     0.012 |     0.000 |     0.000 |     0.008 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.031 |     0.000 |     0.002 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             P |         1 |         1 |         0 |         2 |         0 |        22 |         2 |         3 |         0 |         3 |         0 |         0 |         1 |         1 |         2 |       193 |         3 |         3 |         0 |         1 |         1 |         0 |         1 |         0 |         0 |         0 |       240 | 
##               |     0.004 |     0.004 |     0.000 |     0.008 |     0.000 |     0.092 |     0.008 |     0.013 |     0.000 |     0.013 |     0.000 |     0.000 |     0.004 |     0.004 |     0.008 |     0.804 |     0.013 |     0.013 |     0.000 |     0.004 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.040 | 
##               |     0.004 |     0.004 |     0.000 |     0.008 |     0.000 |     0.095 |     0.008 |     0.015 |     0.000 |     0.014 |     0.000 |     0.000 |     0.004 |     0.004 |     0.008 |     0.889 |     0.013 |     0.012 |     0.000 |     0.004 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.001 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.032 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             Q |         2 |         1 |         2 |         1 |         2 |         0 |         5 |         6 |         0 |         1 |         0 |         1 |         2 |         1 |        17 |         1 |       180 |         4 |         1 |         0 |         3 |         1 |         0 |         0 |         0 |         3 |       234 | 
##               |     0.009 |     0.004 |     0.009 |     0.004 |     0.009 |     0.000 |     0.021 |     0.026 |     0.000 |     0.004 |     0.000 |     0.004 |     0.009 |     0.004 |     0.073 |     0.004 |     0.769 |     0.017 |     0.004 |     0.000 |     0.013 |     0.004 |     0.000 |     0.000 |     0.000 |     0.013 |     0.039 | 
##               |     0.009 |     0.004 |     0.009 |     0.004 |     0.008 |     0.000 |     0.020 |     0.031 |     0.000 |     0.005 |     0.000 |     0.005 |     0.009 |     0.004 |     0.072 |     0.005 |     0.793 |     0.016 |     0.004 |     0.000 |     0.012 |     0.004 |     0.000 |     0.000 |     0.000 |     0.014 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.003 |     0.000 |     0.030 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             R |         3 |        19 |         2 |        12 |         2 |         0 |         3 |         5 |         0 |         0 |         3 |         2 |         0 |         5 |         2 |         0 |         3 |       162 |         0 |         1 |         3 |         0 |         0 |         0 |         0 |         0 |       227 | 
##               |     0.013 |     0.084 |     0.009 |     0.053 |     0.009 |     0.000 |     0.013 |     0.022 |     0.000 |     0.000 |     0.013 |     0.009 |     0.000 |     0.022 |     0.009 |     0.000 |     0.013 |     0.714 |     0.000 |     0.004 |     0.013 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.038 | 
##               |     0.013 |     0.075 |     0.009 |     0.049 |     0.008 |     0.000 |     0.012 |     0.026 |     0.000 |     0.000 |     0.015 |     0.009 |     0.000 |     0.021 |     0.008 |     0.000 |     0.013 |     0.638 |     0.000 |     0.004 |     0.012 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.001 |     0.003 |     0.000 |     0.002 |     0.000 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.027 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             S |         2 |         7 |         0 |         4 |        10 |         2 |         1 |         0 |         1 |         0 |         1 |         1 |         0 |         0 |         1 |         0 |         0 |         2 |       185 |         0 |         0 |         0 |         0 |         2 |         0 |         5 |       224 | 
##               |     0.009 |     0.031 |     0.000 |     0.018 |     0.045 |     0.009 |     0.004 |     0.000 |     0.004 |     0.000 |     0.004 |     0.004 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.009 |     0.826 |     0.000 |     0.000 |     0.000 |     0.000 |     0.009 |     0.000 |     0.022 |     0.037 | 
##               |     0.009 |     0.028 |     0.000 |     0.016 |     0.042 |     0.009 |     0.004 |     0.000 |     0.004 |     0.000 |     0.005 |     0.005 |     0.000 |     0.000 |     0.004 |     0.000 |     0.000 |     0.008 |     0.808 |     0.000 |     0.000 |     0.000 |     0.000 |     0.008 |     0.000 |     0.024 |           | 
##               |     0.000 |     0.001 |     0.000 |     0.001 |     0.002 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.031 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             T |         0 |         0 |         0 |         2 |         1 |         7 |         2 |         0 |         1 |         0 |         0 |         2 |         0 |         0 |         0 |         2 |         1 |         1 |         1 |       205 |         2 |         1 |         0 |         4 |         5 |         1 |       238 | 
##               |     0.000 |     0.000 |     0.000 |     0.008 |     0.004 |     0.029 |     0.008 |     0.000 |     0.004 |     0.000 |     0.000 |     0.008 |     0.000 |     0.000 |     0.000 |     0.008 |     0.004 |     0.004 |     0.004 |     0.861 |     0.008 |     0.004 |     0.000 |     0.017 |     0.021 |     0.004 |     0.040 | 
##               |     0.000 |     0.000 |     0.000 |     0.008 |     0.004 |     0.030 |     0.008 |     0.000 |     0.004 |     0.000 |     0.000 |     0.009 |     0.000 |     0.000 |     0.000 |     0.009 |     0.004 |     0.004 |     0.004 |     0.827 |     0.008 |     0.004 |     0.000 |     0.016 |     0.022 |     0.005 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.034 |     0.000 |     0.000 |     0.000 |     0.001 |     0.001 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             U |         1 |         0 |         3 |         0 |         0 |         0 |         2 |         3 |         0 |         0 |         0 |         1 |         0 |         5 |         1 |         0 |         3 |         0 |         0 |         2 |       220 |         1 |         0 |         0 |         1 |         0 |       243 | 
##               |     0.004 |     0.000 |     0.012 |     0.000 |     0.000 |     0.000 |     0.008 |     0.012 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.021 |     0.004 |     0.000 |     0.012 |     0.000 |     0.000 |     0.008 |     0.905 |     0.004 |     0.000 |     0.000 |     0.004 |     0.000 |     0.041 | 
##               |     0.004 |     0.000 |     0.014 |     0.000 |     0.000 |     0.000 |     0.008 |     0.015 |     0.000 |     0.000 |     0.000 |     0.005 |     0.000 |     0.021 |     0.004 |     0.000 |     0.013 |     0.000 |     0.000 |     0.008 |     0.887 |     0.004 |     0.000 |     0.000 |     0.004 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.037 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             V |         0 |         2 |         0 |         0 |         2 |         0 |         1 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         1 |         1 |         0 |         1 |         0 |       203 |         8 |         0 |         8 |         0 |       229 | 
##               |     0.000 |     0.009 |     0.000 |     0.000 |     0.009 |     0.000 |     0.004 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.004 |     0.004 |     0.000 |     0.004 |     0.000 |     0.886 |     0.035 |     0.000 |     0.035 |     0.000 |     0.038 | 
##               |     0.000 |     0.008 |     0.000 |     0.000 |     0.008 |     0.000 |     0.004 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.005 |     0.004 |     0.004 |     0.000 |     0.004 |     0.000 |     0.890 |     0.035 |     0.000 |     0.035 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.034 |     0.001 |     0.000 |     0.001 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             W |         0 |         0 |         0 |         0 |         1 |         0 |         1 |         0 |         0 |         0 |         0 |         0 |         4 |         1 |         2 |         1 |         0 |         0 |         0 |         0 |         0 |         3 |       212 |         0 |         0 |         0 |       225 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.018 |     0.004 |     0.009 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.013 |     0.942 |     0.000 |     0.000 |     0.000 |     0.038 | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.017 |     0.004 |     0.008 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.013 |     0.918 |     0.000 |     0.000 |     0.000 |           | 
##               |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.035 |     0.000 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             X |         0 |         4 |         0 |         2 |        13 |         0 |         0 |         3 |         0 |         1 |         3 |         1 |         0 |         0 |         1 |         0 |         1 |         0 |         1 |         4 |         1 |         0 |         0 |       199 |         2 |         0 |       236 | 
##               |     0.000 |     0.017 |     0.000 |     0.008 |     0.055 |     0.000 |     0.000 |     0.013 |     0.000 |     0.004 |     0.013 |     0.004 |     0.000 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.004 |     0.017 |     0.004 |     0.000 |     0.000 |     0.843 |     0.008 |     0.000 |     0.039 | 
##               |     0.000 |     0.016 |     0.000 |     0.008 |     0.055 |     0.000 |     0.000 |     0.015 |     0.000 |     0.005 |     0.015 |     0.005 |     0.000 |     0.000 |     0.004 |     0.000 |     0.004 |     0.000 |     0.004 |     0.016 |     0.004 |     0.000 |     0.000 |     0.787 |     0.009 |     0.000 |           | 
##               |     0.000 |     0.001 |     0.000 |     0.000 |     0.002 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.000 |     0.000 |     0.033 |     0.000 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             Y |         0 |         3 |         0 |         3 |         0 |         3 |         3 |         1 |         0 |         1 |         2 |         0 |         1 |         2 |         0 |         1 |         1 |         3 |         0 |        14 |         0 |         4 |         0 |         1 |       192 |         0 |       235 | 
##               |     0.000 |     0.013 |     0.000 |     0.013 |     0.000 |     0.013 |     0.013 |     0.004 |     0.000 |     0.004 |     0.009 |     0.000 |     0.004 |     0.009 |     0.000 |     0.004 |     0.004 |     0.013 |     0.000 |     0.060 |     0.000 |     0.017 |     0.000 |     0.004 |     0.817 |     0.000 |     0.039 | 
##               |     0.000 |     0.012 |     0.000 |     0.012 |     0.000 |     0.013 |     0.012 |     0.005 |     0.000 |     0.005 |     0.010 |     0.000 |     0.004 |     0.008 |     0.000 |     0.005 |     0.004 |     0.012 |     0.000 |     0.056 |     0.000 |     0.018 |     0.000 |     0.004 |     0.846 |     0.000 |           | 
##               |     0.000 |     0.001 |     0.000 |     0.001 |     0.000 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.002 |     0.000 |     0.001 |     0.000 |     0.000 |     0.032 |     0.000 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##             Z |         0 |         8 |         0 |         3 |         3 |         3 |         1 |         1 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         1 |         1 |         2 |         0 |         0 |         0 |         0 |         6 |         1 |       190 |       220 | 
##               |     0.000 |     0.036 |     0.000 |     0.014 |     0.014 |     0.014 |     0.005 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.005 |     0.005 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.027 |     0.005 |     0.864 |     0.037 | 
##               |     0.000 |     0.032 |     0.000 |     0.012 |     0.013 |     0.013 |     0.004 |     0.005 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.004 |     0.004 |     0.009 |     0.000 |     0.000 |     0.000 |     0.000 |     0.024 |     0.004 |     0.905 |           | 
##               |     0.000 |     0.001 |     0.000 |     0.001 |     0.001 |     0.001 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.000 |     0.001 |     0.000 |     0.032 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
##  Column Total |       233 |       252 |       214 |       245 |       238 |       232 |       246 |       194 |       223 |       212 |       202 |       213 |       231 |       242 |       236 |       217 |       227 |       254 |       229 |       248 |       248 |       228 |       231 |       253 |       227 |       210 |      5985 | 
##               |     0.039 |     0.042 |     0.036 |     0.041 |     0.040 |     0.039 |     0.041 |     0.032 |     0.037 |     0.035 |     0.034 |     0.036 |     0.039 |     0.040 |     0.039 |     0.036 |     0.038 |     0.042 |     0.038 |     0.041 |     0.041 |     0.038 |     0.039 |     0.042 |     0.038 |     0.035 |           | 
## --------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
## 
## </code></pre>
<pre class="r"><code># Calculate prediction success rate for all letters
mean(diag(s$prop.col))</code></pre>
<pre><code>## [1] 0.833701</code></pre>
<pre class="r"><code># Check prediction success rate for each letter
diag(s$prop.col)</code></pre>
<pre><code>##         A         B         C         D         E         F         G 
## 0.9098712 0.6547619 0.9252336 0.7510204 0.7478992 0.8017241 0.7601626 
##         H         I         J         K         L         M         N 
## 0.7216495 0.9058296 0.9150943 0.8762376 0.9248826 0.9307359 0.8760331 
##         O         P         Q         R         S         T         U 
## 0.7881356 0.8894009 0.7929515 0.6377953 0.8078603 0.8266129 0.8870968 
##         V         W         X         Y         Z 
## 0.8903509 0.9177489 0.7865613 0.8458150 0.9047619</code></pre>
<p>Even when all SVD variables (16) were used, the prediction rate is around 93.4% (lower than the original of 94.8%). When we use less (e.g. 8), the prediction rate is getting worst (83.4%). It seems that SVD does not help us improve the prediction model. Almost all original variables have variability (add information) so they are useful for predicting the letter</p>
</div>
<div id="hierarchical-clustering" class="section level2">
<h2><strong>Hierarchical clustering</strong></h2>
<p>In this part of the analysis the objective is to assign the cases into clusters. Cluster analysis or clustering is the task of grouping a set of objects in such a way that objects in the same group (called a cluster) are more similar (in some sense or another) to each other than to those in other groups (clusters). Finally i build a hierarchical clustering model in order to understand which letters are “closer” to others and maybe missclasified. We applied it on the pre-proccessed data set (letter.cluster).</p>
<pre class="r"><code># Tranform the summary dataset to a dataframe
letter.cluster &lt;- as.data.frame(letter.cluster)

# Assign letters variable as rownames
rownames(letter.cluster) &lt;- letter.cluster$lettr

# Run the hierarchical clustering 
clusters &lt;- hclust(dist(letter.cluster))</code></pre>
<p>At the plot below you can see the hierarchical clustering output. When we compare these results with the missclasification rates of the original model, it seems that for some letters like “B”, “D”, “F” it looks relevant. For other letters such “A”, “C” don’t match.</p>
<pre class="r"><code># Plot the dendogram
ggdendrogram(clusters, rotate = TRUE, size = 2)+
  labs(title = &quot;Dendogram of hierarchical clustering model&quot;)</code></pre>
<p><img src="/post/2017-12-28-build-a-letter-recognition-classifier_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
</div>
</div>
<div id="results" class="section level1">
<h1>RESULTS</h1>
<p>Finally, after testing various models using k-NN algorithm, the best model used the original predictors &amp; 3 nearest neighbors (k=3). The accuracy obtained from from the final model is <strong>94,8%</strong>. I also tried the <strong>SVD technique</strong> in order to check if the new uncorrelated variables would help us improve the prediction accuracy rate of the letter in a new observation. But the model wasn’t improved.</p>
</div>

                </section>
            </article>

            
                
<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
<a class="a2a_dd" href="https://www.addtoany.com/share"></a>
<a class="a2a_button_linkedin"></a>
<a class="a2a_button_twitter"></a>
<a class="a2a_button_facebook"></a>
<a class="a2a_button_google_plus"></a>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>



            

            

            

            <footer id="footer">
    
        <div id="social">

	
	
    <a class="symbol" href="https://github.com/mantoniou">
        <i class="fa fa-github-square"></i>
    </a>
    
    <a class="symbol" href="https://www.linkedin.com/in/manos-antoniou-a558001b">
        <i class="fa fa-linkedin-square"></i>
    </a>
    
    <a class="symbol" href="https://twitter.com/mantoniou1">
        <i class="fa fa-twitter-square"></i>
    </a>
    


</div>

    
    <p class="small">
    
       © Copyright 2018 Manos Antoniou 
    
    </p>
</footer>

        </section>

        <script src="/js/jquery-3.3.1.min.js"></script>
<script src="/js/main.js"></script>
<script src="/js/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>




  
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-116714552-1', 'auto');
ga('send', 'pageview');
</script>





    </body>
</html>
